import logging
from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from src import config

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def create_spark_session(app_name: str = "EcommerceAnalytics") -> SparkSession:
    """Initializes and returns a PySpark session."""
    logger.info("Initializing Spark session...")
    return SparkSession.builder \
        .appName(app_name) \
        .config("spark.sql.shuffle.partitions", "4") \
        .getOrCreate()

def load_csv(spark: SparkSession, filepath: str) -> DataFrame:
    """Loads a CSV file into a Spark DataFrame."""
    logger.info(f"Loading data from {filepath}...")
    return spark.read.csv(filepath, header=True, inferSchema=True)

def calculate_revenue_per_product(orders_df: DataFrame, products_df: DataFrame) -> DataFrame:
    """Calculates total revenue generated by each product."""
    logger.info("Calculating revenue per product...")
    joined_df = orders_df.join(products_df, "product_id")
    
    revenue_df = joined_df.withColumn("total_price", F.col("quantity") * F.col("price"))
    
    return revenue_df.groupBy("product_id", "product_name") \
        .agg(F.round(F.sum("total_price"), 2).alias("total_revenue")) \
        .orderBy(F.desc("total_revenue"))

def calculate_top_customers(orders_df: DataFrame, customers_df: DataFrame, products_df: DataFrame) -> DataFrame:
    """Identifies customers who have spent the most money."""
    logger.info("Calculating top customers by spend...")
    joined_df = orders_df.join(products_df, "product_id").join(customers_df, "customer_id")
    
    spend_df = joined_df.withColumn("spend", F.col("quantity") * F.col("price"))
    
    return spend_df.groupBy("customer_id", "name", "email") \
        .agg(F.round(F.sum("spend"), 2).alias("total_spent")) \
        .orderBy(F.desc("total_spent"))

def save_results(df: DataFrame, folder_name: str) -> None:
    """Saves a Spark DataFrame to the processed data directory as a single CSV."""
    output_path = str(config.PROCESSED_DATA_DIR / folder_name)
    logger.info(f"Saving results to {output_path}...")
    
    # Coalesce to 1 partition to save as a single CSV file for easier viewing in this local project
    df.coalesce(1).write.csv(output_path, header=True, mode="overwrite")

def main() -> None:
    """Main execution function for Spark analytics."""
    spark = None
    try:
        spark = create_spark_session()

        # Load Data
        customers_df = load_csv(spark, str(config.CUSTOMERS_FILE))
        products_df = load_csv(spark, str(config.PRODUCTS_FILE))
        orders_df = load_csv(spark, str(config.ORDERS_FILE))

        # Transformations & Analytics
        product_revenue_df = calculate_revenue_per_product(orders_df, products_df)
        top_customers_df = calculate_top_customers(orders_df, customers_df, products_df)

        # Show previews in the console
        logger.info("Preview: Top Products by Revenue")
        product_revenue_df.show(5)
        
        logger.info("Preview: Top Customers by Spend")
        top_customers_df.show(5)

        # Save processed insights
        save_results(product_revenue_df, "product_revenue")
        save_results(top_customers_df, "top_customers")

        logger.info("Spark analytics pipeline completed successfully.")
        
    except Exception as e:
        logger.error(f"Spark pipeline failed: {e}")
    finally:
        if spark:
            spark.stop()
            logger.info("Spark session stopped.")

if __name__ == "__main__":
    main()